FROM node:22.12-bookworm-slim

WORKDIR /app

RUN npm config set registry https://registry.npmmirror.com
RUN npm install -g @angular/cli

COPY package*.json /app

RUN npm install

COPY . .

EXPOSE 4200

CMD ["ng", "serve"]
